import { ReferenceSection } from "@study-game/engine";

export const MPEP_SECTION_151: ReferenceSection[] = [
  {
    id: "mpep-151-00",
    number: "151",
    title: "Content and Filing of Statements — Overview",
    content:
      "This section details the requirements for the statements that must be filed by patent applicants in response to 45-day letters issued under MPEP 150. When the Department of Energy (DOE) or the National Aeronautics and Space Administration (NASA) identifies a patent application as potentially involving an invention made under a government contract, the applicant must file a statement establishing their rights. The statement serves as the applicant's formal response to the government's claim of property interest and must contain specific information about the government contract, the relationship between the invention and the contract, and the government's rights in the invention. MPEP 151 specifies the content requirements for these statements, addresses special situations involving multiple inventors, and provides guidance on substitute statements when an inventor is unavailable. Proper compliance with these requirements is essential to avoid abandonment of the application and to ensure that the government's property interests are addressed transparently. Practitioners should review the specific requirements carefully, as the statement must be factually accurate and complete to satisfy both the USPTO and the relevant government agency.",
  },
  {
    id: "mpep-151-01",
    number: "151.01",
    title: "Required Content of the Statement",
    content:
      "The statement filed in response to a 45-day letter must include three core elements. First, the statement must contain an identification of the government contract under which the invention was made or conceived. This identification should include the contract number, the name of the contracting agency (DOE or NASA), and sufficient detail to allow the agency to locate and verify the contract. For example, a DOE contract might be identified as 'DOE Contract DE-AC05-1234' and a NASA contract as 'NASA Contract NNX-5678.' Second, the statement must address whether the invention was made or conceived during the performance of work under the identified contract. This element requires the applicant to describe the circumstances of the invention's creation, including whether it arose from contract-funded research, used contract-provided facilities or materials, or was otherwise connected to contract performance. The applicant should be specific about the relationship between the inventive work and the contract scope. Third, the statement must describe the rights of the government in the invention. This includes whether the government holds a license (exclusive or nonexclusive), claims title to the invention, or has waived its rights. If a waiver has been requested or granted, the statement should describe the waiver's terms. The statement must be factually accurate, as misrepresentations can have serious consequences for the applicant's patent rights and may constitute fraud on the USPTO.",
  },
  {
    id: "mpep-151-02",
    number: "151.02",
    title: "Government Rights and Waiver Provisions",
    content:
      "The government's rights in a contractor invention can take several forms, and the statement must accurately describe which rights apply. The most significant right is title: both DOE under 42 U.S.C. 2182 and NASA under 51 U.S.C. 20135 may claim title to inventions made under their respective contracts. If the agency claims title, the contractor may be required to assign the patent application to the government. Alternatively, the agency may assert a license interest rather than full title. Government licenses in contractor inventions are typically nonexclusive, irrevocable, and royalty-free, allowing the government to practice the invention for government purposes while the contractor retains title and the right to license commercially. Both DOE and NASA have waiver provisions that allow contractors to retain greater rights in their inventions. To obtain a waiver, the contractor must affirmatively request it and demonstrate that contractor retention of rights will better serve the public interest. Factors considered in waiver evaluations include the contractor's commercialization plans, the potential for public benefit, the government's own need for the technology, and the relative investment of the contractor versus the government. If a waiver is granted, the government typically retains at minimum a nonexclusive license. The waiver process is separate from the statement filing requirement, and a waiver request does not extend the 30-day deadline for filing the statement. Practitioners are advised to file the statement timely while simultaneously pursuing any waiver requests through the appropriate agency channels.",
  },
  {
    id: "mpep-151-03",
    number: "151.03",
    title: "Multiple Inventors and Joint Applications",
    content:
      "Special rules apply when a patent application subject to DOE or NASA interest names multiple inventors. Each inventor who was involved in the government contract must file a separate statement addressing their individual relationship to the contract and the invention. Statements cannot be combined or filed jointly; each contract-involved inventor has an independent obligation to respond. When some inventors on the application worked under the government contract and others did not, only those inventors who were under the contract are required to file statements. Inventors who developed their contributions independently, without any connection to a government contract, are not required to file. However, the government's property rights may still affect the entire application even if not all inventors were under the contract. For example, if two of four inventors worked under a DOE contract and the other two worked independently, the two contract inventors must each file a statement, while the independent inventors need not. Nevertheless, DOE may still have property rights in the aspects of the invention contributed by the contract inventors. In such cases, the government's rights typically attach to the portions of the invention that arose from contract-funded work, and the resolution of rights may be complex. Practitioners should advise all inventors on the application of the 45-day letter and the response requirements, even if some inventors are not required to file, to ensure coordinated and consistent responses.",
  },
  {
    id: "mpep-151-04",
    number: "151.04",
    title: "Substitute Statements and Special Circumstances",
    content:
      "In certain circumstances, an inventor required to file a statement may be unavailable to do so. MPEP 151 provides for substitute statements when the inventor cannot be reached or refuses to cooperate. A substitute statement may be filed by any party who has sufficient knowledge of the facts necessary to address the required content elements — typically the assignee, an obligated assignee, or another person with direct knowledge of the contract and invention circumstances. The substitute statement must contain all the same substantive elements as a regular statement: identification of the government contract, whether the invention was made under the contract, and the government's rights. In addition, the substitute statement must include an explanation of why the inventor is unavailable. The explanation should describe the efforts made to locate or contact the inventor, the reasons for the inventor's unavailability (such as being deceased, having moved to another country, or refusing to cooperate), and the basis for the filer's knowledge of the relevant facts. The filing of a substitute statement does not extend the 30-day response deadline. The substitute statement must be filed within the same 30-day period as a regular statement. If the inventor later becomes available, the agency may request an additional statement directly from the inventor. Practitioners should document their efforts to reach unavailable inventors thoroughly, as the adequacy of the substitute statement and the explanation of unavailability may be evaluated by both the USPTO and the relevant government agency.",
  },
];
