import { ReferenceSection } from "@study-game/engine";

export const MPEP_SECTION_102: ReferenceSection[] = [
  {
    id: "mpep-102-00",
    number: "102",
    title: "Access to Patent Application Files",
    content:
      "MPEP Section 102 governs the rules and procedures for public access to patent application files maintained by the United States Patent and Trademark Office (USPTO). The access framework is primarily established by 37 C.F.R. 1.14, which creates a structured system distinguishing between applications that are open to public inspection and those that remain confidential. The fundamental principle is that once an application has been published under 35 U.S.C. 122(b) or has resulted in a granted patent, the application file becomes available for public inspection under 37 C.F.R. 1.14(a). Conversely, pending unpublished applications are maintained in confidence under 37 C.F.R. 1.14(b), consistent with the confidentiality mandate of 35 U.S.C. 122(a). The access rules also address several intermediate categories, including abandoned applications, status information, and applications that have been referenced in other publicly available records. The framework balances two competing interests: protecting the confidentiality of applicants' proprietary information during prosecution, and ensuring that the public has access to patent information necessary for evaluating patent rights and conducting freedom-to-operate analyses. Access to published and patented files is generally unrestricted, while access to pending unpublished applications requires either the applicant's written authority or a petition demonstrating special circumstances. The USPTO provides most public access through its online Patent Application Information Retrieval (PAIR) system and the Patent Center portal, where published applications and granted patents can be viewed in their entirety.",
  },
  {
    id: "mpep-102-01",
    number: "102.01",
    title: "Public Access to Published and Patented Files",
    content:
      "Under 37 C.F.R. 1.14(a), patent application files that have been published under 35 U.S.C. 122(b) or that have resulted in the issuance of a U.S. patent are open to public inspection. This means that any member of the public may access and obtain copies of the complete application file, including the specification, claims, drawings, correspondence between the applicant and the examiner (prosecution history or file wrapper), and all other papers associated with the application. For published applications, public access begins on the date of publication. The publication itself is made available through the USPTO's online databases, and the complete application file — including any amendments, office actions, and applicant responses filed up to the date of publication — becomes accessible. Papers filed after publication also become part of the publicly available record as they are added to the file. For granted patents, the entire prosecution history is open to public inspection from the date of patent grant. This includes all papers from the initial filing through the issuance of the patent, as well as any post-grant papers such as certificates of correction, maintenance fee records, and reissue or reexamination proceedings. Access to published and patented files does not require a petition, payment of a special fee, or the applicant's authorization. The public can access these files through the USPTO's Patent Center, Public PAIR, or by visiting the USPTO's public search facilities in Alexandria, Virginia. Certified copies of file contents may also be ordered for a fee under 37 C.F.R. 1.19.",
  },
  {
    id: "mpep-102-02",
    number: "102.02",
    title: "Access to Pending Unpublished Applications",
    content:
      "Under 37 C.F.R. 1.14(b), applications that are pending and have not yet been published are maintained in confidence. No member of the public may access the file of a pending unpublished application except in limited circumstances. The default rule is that such applications are treated as confidential under 35 U.S.C. 122(a), and the USPTO will not confirm or deny the existence of a pending unpublished application to third-party requesters. There are several narrow exceptions to this rule. First, the applicant or an authorized representative may access the file at any time during pendency. Second, under 37 C.F.R. 1.14(c), an applicant may provide written authority for a named person to access the application file. The written authority must be signed by the applicant or the applicant's representative and must identify the specific application by application number. Third, access may be granted by petition under certain circumstances. A petition for access to a pending unpublished application under 37 C.F.R. 1.14(i) may be granted if the petitioner establishes that special circumstances warrant access — for example, if the petitioner can show that access is necessary to determine whether a duty of candor has been satisfied or to enforce a legal right. The petition must include the fee set forth in 37 C.F.R. 1.17(g) and a detailed explanation of the circumstances justifying access. The decision to grant or deny the petition is within the discretion of the USPTO. Pending unpublished applications include provisionals, applications subject to non-publication requests, and applications still within the 18-month pre-publication window. Design patent applications remain unpublished throughout their entire prosecution, from filing until grant.",
  },
  {
    id: "mpep-102-03",
    number: "102.03",
    title: "Status Information",
    content:
      "Under 37 C.F.R. 1.14(e), the USPTO will provide certain limited status information about patent applications to third parties, even for applications that have not yet been published. Status information is a narrow category of information that does not reveal the substance of the application. Specifically, 37 C.F.R. 1.14(e) provides that status information includes: (1) whether the application is pending, abandoned, or patented; (2) whether the application has been published under 35 U.S.C. 122(b); and (3) the application number and filing date. Importantly, status information does not include the contents of the application, the names of the inventors or applicants, the title of the invention, or any substantive information about the claims or specification. The rationale for making status information available is to allow third parties to determine the procedural posture of an application without compromising the confidentiality of its contents. This is particularly useful for parties involved in licensing negotiations, litigation, or prior art searches who need to know whether a particular application is still pending. To obtain status information for an unpublished application, the requester must identify the application by its application number. The USPTO will not conduct searches to identify applications based on other criteria (such as inventor name or subject matter) for unpublished applications. For published applications and patents, status information is freely available through the USPTO's online databases without restriction. The availability of status information represents a carefully calibrated exception to the general confidentiality rules, providing procedural transparency without sacrificing substantive confidentiality.",
  },
  {
    id: "mpep-102-04",
    number: "102.04",
    title: "Access to Abandoned Applications",
    content:
      "The rules governing access to abandoned applications depend on whether the abandoned application has been referenced in certain publicly available records. Under 37 C.F.R. 1.14(a)(1)(iv), an abandoned application becomes open to public inspection if it is identified or relied upon in a U.S. patent, a statutory invention registration, a U.S. patent application publication, or an international publication of an international application that designates the United States. In such cases, the abandoned application is treated the same as a published or patented application for access purposes, and any member of the public may inspect the file without a petition. The rationale for this rule is that once an abandoned application has been referenced in a public patent document, the public has a legitimate interest in reviewing the abandoned application to understand the scope and context of the reference. For example, if a granted patent claims the benefit of an earlier-filed application that was subsequently abandoned, the public should be able to review the abandoned parent application to understand the priority chain and the disclosure available at each filing date. For abandoned applications that have not been referenced in any publicly available patent document, access remains restricted. These applications are treated as unpublished and confidential, consistent with the general confidentiality rules of 35 U.S.C. 122(a). A third party seeking access to an unreferenced abandoned application must file a petition under 37 C.F.R. 1.14(i). The petition must demonstrate that access is warranted by special circumstances — for instance, if the petitioner needs to determine the effective filing date of a related application or to establish prior art status. The petition requires the fee under 37 C.F.R. 1.17(g) and is decided at the discretion of the Office. Applicants should be aware that abandoning an application does not guarantee permanent confidentiality; if the application is later referenced in a public record, the file will become publicly accessible.",
  },
];
