import { ReferenceSection } from "@study-game/engine";

export const MPEP_SECTION_106: ReferenceSection[] = [
  {
    id: "mpep-106-00",
    number: "106",
    title: "Assignee Control and Inspection Rights",
    content:
      "This section covers the rights and procedures related to assignee control of patent applications and the rules governing inspection of application files. Under the patent system, an inventor who assigns their patent rights to another entity transfers significant control over the application. The assignee's rights are governed primarily by 37 CFR 3.71 (right to take action) and 37 CFR 3.73 (establishing entitlement through a statement of assignee interest). The extent of the assignee's control depends on whether the assignment covers the entire right, title, and interest or only a partial interest. Additionally, because unpublished patent applications are maintained in confidence under 35 USC 122(a), specific rules govern who may inspect the application file and under what conditions. These rules balance the need for application confidentiality with the legitimate interests of assignees, inventors, and authorized third parties. The intersection of assignee control and inspection rights is particularly important for corporate patent portfolios, licensing arrangements, and due diligence activities.",
  },
  {
    id: "mpep-106-01",
    number: "106.01",
    title: "Assignee Right to Take Action: 37 CFR 3.71 and 3.73",
    content:
      "Under 37 CFR 3.71, an assignee of the entire right, title, and interest in a patent application may take action in the application to the exclusion of the inventor. This means the assignee can respond to office actions, amend claims, file continuations, appeal rejections, and make all substantive decisions regarding prosecution. The assignee effectively steps into the inventor's shoes for purposes of patent prosecution.\n\nTo establish the right to take action, 37 CFR 3.73(c) requires the assignee to file a statement setting forth the basis for the assignee's entitlement. This statement must be supported by documentary evidence establishing the chain of title from the named inventor to the current assignee. The chain of title documentation typically includes the assignment agreement, any intermediate assignments (if the rights passed through multiple entities), and evidence of corporate transactions such as mergers or name changes.\n\nOnce the 3.73(c) statement is properly filed, the assignee gains several important powers. The assignee may appoint and revoke powers of attorney, designating which registered practitioners handle the application. The assignee may revoke a power of attorney previously granted by the inventor and appoint a new registered practitioner without the inventor's consent. The assignee controls the direction of prosecution, including claim strategy and response content.\n\nEven when the assignee controls prosecution, the inventor retains certain rights. The inventor has the right to receive notice of all USPTO actions on the application and the right to inspect the application file. However, the inventor cannot override the assignee's prosecution decisions.",
  },
  {
    id: "mpep-106-02",
    number: "106.02",
    title: "Partial Interest Holders: Limited Rights",
    content:
      "A partial assignee — an entity that holds less than the entire right, title, and interest in a patent application — has significantly limited rights compared to a full assignee. Under 37 CFR 3.71, a partial assignee may inspect the application file, gaining access to review the specification, claims, prosecution history, and office actions. However, a partial assignee may not unilaterally direct prosecution, amend claims, respond to office actions, or make any substantive decisions about the application.\n\nThe rationale for this limitation is that patent prosecution decisions affect the entire application, and no single partial interest holder should be able to make unilateral decisions that affect other interest holders. If a partial assignee could independently amend claims, for example, this could prejudice the interests of other partial assignees or the inventor.\n\nWhen there are multiple partial assignees, all of them together with the inventor must join to take action in the application. This means that every partial interest holder and the inventor must agree before any prosecution action can be taken. There is no provision for majority voting or any mechanism to override a dissenting partial assignee.\n\nThis unanimity requirement can create practical challenges. If partial assignees disagree about prosecution strategy, the application may stall. In practice, the most effective resolution is for one entity to acquire the interests of all other parties and become the assignee of the entire right, title, and interest. Alternatively, the parties may enter into a joint management agreement that establishes a framework for resolving disputes outside the USPTO process.",
  },
  {
    id: "mpep-106-03",
    number: "106.03",
    title: "Third-Party Access and Written Consent Requirements",
    content:
      "Under 35 USC 122(a), patent applications are maintained in confidence by the USPTO. No information about a pending, unpublished application may be disclosed without the authority of the applicant. This statutory confidentiality requirement is one of the most important protections in the patent system, ensuring that applicants' inventions are not prematurely disclosed to competitors or the public.\n\nFor a third party to access an unpublished patent application, written authorization from the applicant or the assignee who has established their interest under 37 CFR 3.73 is required. Oral consent is not sufficient; the authorization must be in writing. The written consent should identify the application by serial number, identify the third party being authorized, and specify the scope of the authorized access.\n\nThe assignee who has established their interest under 37 CFR 3.73 has the right to control who may inspect the application. This means the assignee can grant or deny inspection access to potential licensees, investors, acquirers, or other interested parties. When partial assignees are involved, all partial assignees together with the inventor must join to authorize third-party access, consistent with the general rule under 37 CFR 3.71.\n\nThe confidentiality requirement and written consent obligation cease once the application is published (typically at 18 months from the earliest filing date) or once a patent issues. At that point, the application file becomes part of the public record and is freely accessible to anyone through the USPTO's Patent Application Information Retrieval (PAIR) system or at the Patent File Repository. No written consent is needed to access published applications or issued patent files.",
  },
  {
    id: "mpep-106-04",
    number: "106.04",
    title: "Inventor Rights After Assignment and Power of Attorney Management",
    content:
      "When an inventor assigns the entire right, title, and interest in a patent application to an assignee, the balance of control shifts significantly. However, the inventor does not lose all rights in the application. Understanding the division of rights between the inventor and the assignee after assignment is important for both practitioners and their clients.\n\nRights retained by the inventor after full assignment include the right to receive notice of all USPTO actions on the application, including office actions, notices of allowance, and other correspondence. The inventor also retains the right to inspect the application file at any time. These retained rights ensure that the inventor remains informed about the status and prosecution of their invention.\n\nRights transferred to the assignee include the right to direct prosecution (including claim amendments, responses to office actions, and appeals), the right to appoint and revoke powers of attorney, the right to control inspection access for third parties, the right to file continuation, divisional, and continuation-in-part applications, and the right to abandon the application.\n\nRegarding power of attorney management, the assignee of the entire interest has full authority to manage the power of attorney. The assignee may revoke a power of attorney previously granted by the inventor without the inventor's consent and without needing approval from the Commissioner for Patents. The assignee may then appoint a new registered practitioner of its choosing. This authority is critical in situations where the assignee and inventor have different preferences regarding legal representation, or when the practitioner of record becomes unavailable due to suspension, exclusion, retirement, or other circumstances.\n\nPractitioners should be aware that when representing an inventor who has assigned their rights, the practitioner's ultimate duty may be to the assignee who controls prosecution, depending on the specific representation arrangement. Clear engagement agreements should address this potential complexity.",
  },
];
